from src.Util.httpRequest import *
# import ipdb
# ipdb.set_trace()

TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiJodHRwczovL29yZ2Q1ZGNhMzE5LmNybS5keW5hbWljcy5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvY2E0ZWIzZjUtNjkyNi00N2E2LWI1MGQtMDU0YTRkMzZkZmRkLyIsImlhdCI6MTYwNTIyNzYwOSwibmJmIjoxNjA1MjI3NjA5LCJleHAiOjE2MDUyMzE1MDksImFpbyI6IkUyUmdZRWlVbnpqemJoSGpDUzFWOTd1dlU4NWxBZ0E9IiwiYXBwaWQiOiIyZTkxNDJhMC1iMTQ4LTQyMWYtYWI1NC0zYjc1NTc4MjQ1MzQiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9jYTRlYjNmNS02OTI2LTQ3YTYtYjUwZC0wNTRhNGQzNmRmZGQvIiwib2lkIjoiZjdmNmQ5MTAtYzllZi00MjUyLWJjMWYtOTFhNGU5NGY1OThmIiwicmgiOiIwLkFBQUE5Yk5PeWlacHBrZTFEUVZLVFRiZjNhQkNrUzVJc1I5Q3ExUTdkVmVDUlRRU0FBQS4iLCJzdWIiOiJmN2Y2ZDkxMC1jOWVmLTQyNTItYmMxZi05MWE0ZTk0ZjU5OGYiLCJ0aWQiOiJjYTRlYjNmNS02OTI2LTQ3YTYtYjUwZC0wNTRhNGQzNmRmZGQiLCJ1dGkiOiJTX0hzNDdreTgwVzRvd2hFWmNBbEFnIiwidmVyIjoiMS4wIn0.jgKA3T7GE8THvrh7IvXDvuxY-fXBI_DMlaZzgbw1-iiVXjxJ9tZ_scC7INW06DSEMhM_EjjmVE_28Ld0k0A6y0efCkHsoJjMc-_vXtgKNf05g9nSlnA-cQsrTkP6qWkkEkIbc0vro_0gcxuSmgnQ9NcjUDvHn4qjPXA5e1rRl8AnRtntEaJG5qCzkeIHMRN9SL5teIugMH5GII-JXBdgF5bcbfkZpQtVgx-NF9QstG8AXhEHAHa354wkSzR2wFlFsAdkPdGg9GUozOMKAiposob1FatunSlyBGomoCXugNxMzWZL1C-oHHuT2MX-HSFki0Kb9WYViU0Fho2KGTdrRQ"


def get_all():

    print("running")
    # headers = {
    #     "Authorization": "Bearer " + TOKEN,
    #     "Content-Type": "application/json"
    # }

    # http.get(' https://orgd5dca319.crm.dynamics.com/api/data/v9.1/',
    #          headers=headers)


get_all()
